// <auto-generated />
namespace Dominio.Contexto.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Ticket_EdadPaciente : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Ticket_EdadPaciente));
        
        string IMigrationMetadata.Id
        {
            get { return "201911051402262_Ticket_EdadPaciente"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
