// <auto-generated />
namespace Dominio.Contexto.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class AreaLaboratorio_TranscripcionErroneaInoportuna : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AreaLaboratorio_TranscripcionErroneaInoportuna));
        
        string IMigrationMetadata.Id
        {
            get { return "201906101459493_AreaLaboratorio_TranscripcionErroneaInoportuna"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
