// <auto-generated />
namespace Dominio.Contexto.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Ticket_IdImpresionRevision : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Ticket_IdImpresionRevision));
        
        string IMigrationMetadata.Id
        {
            get { return "201910301809595_Ticket_IdImpresionRevision"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
