// <auto-generated />
namespace Dominio.Contexto.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class IpLogueo : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(IpLogueo));
        
        string IMigrationMetadata.Id
        {
            get { return "201906182025162_IpLogueo"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
