// <auto-generated />
namespace Dominio.Contexto.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class PacienteSinResultado_ResultadoNoRegistrado : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(PacienteSinResultado_ResultadoNoRegistrado));
        
        string IMigrationMetadata.Id
        {
            get { return "201911041654089_PacienteSinResultado_ResultadoNoRegistrado"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
